project_id: "586189"
api_token_env: CROWDIN_PERSONAL_TOKEN

files:
  - source: /docs/source/locales/pot/*.pot
    translation: /docs/source/locales/%locale_with_underscore%/LC_MESSAGES/%file_name%.po
